/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.21.9
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-ts code generator program.
 * https://github.com/DestinyItemManager/bungie-api-ts
 * Do not edit these files manually.
 */
import { GeneralUser } from '../user/interfaces.js';
import { GroupResponse } from '../groupv2/interfaces.js';
import { IgnoreResponse, TagResponse } from '../platform.js';
import { PagedQuery } from '../common.js';
/**
 * This enum represents a set of flags - use bitwise operators to check which of
 * these match your value.
 */
export declare const ForumTopicsCategoryFiltersEnum: {
  readonly None: 0;
  readonly Links: 1;
  readonly Questions: 2;
  readonly AnsweredQuestions: 4;
  readonly Media: 8;
  readonly TextOnly: 16;
  readonly Announcement: 32;
  readonly BungieOfficial: 64;
  readonly Polls: 128;
};
export type ForumTopicsCategoryFiltersEnum =
  (typeof ForumTopicsCategoryFiltersEnum)[keyof typeof ForumTopicsCategoryFiltersEnum];
export declare const ForumTopicsQuickDateEnum: {
  readonly All: 0;
  readonly LastYear: 1;
  readonly LastMonth: 2;
  readonly LastWeek: 3;
  readonly LastDay: 4;
};
export type ForumTopicsQuickDateEnum =
  (typeof ForumTopicsQuickDateEnum)[keyof typeof ForumTopicsQuickDateEnum];
export declare const ForumTopicsSortEnum: {
  readonly Default: 0;
  readonly LastReplied: 1;
  readonly MostReplied: 2;
  readonly Popularity: 3;
  readonly Controversiality: 4;
  readonly Liked: 5;
  readonly HighestRated: 6;
  readonly MostUpvoted: 7;
};
export type ForumTopicsSortEnum = (typeof ForumTopicsSortEnum)[keyof typeof ForumTopicsSortEnum];
export declare const ForumPostSortEnum: {
  readonly Default: 0;
  readonly OldestFirst: 1;
};
export type ForumPostSortEnum = (typeof ForumPostSortEnum)[keyof typeof ForumPostSortEnum];
export interface PostSearchResponse {
  readonly relatedPosts: PostResponse[];
  readonly authors: GeneralUser[];
  readonly groups: GroupResponse[];
  readonly searchedTags: TagResponse[];
  readonly polls: PollResponse[];
  readonly recruitmentDetails: ForumRecruitmentDetail[];
  readonly availablePages?: number;
  readonly results: PostResponse[];
  readonly totalResults: number;
  readonly hasMore: boolean;
  readonly query: PagedQuery;
  readonly replacementContinuationToken: string;
  /**
   * If useTotalResults is true, then totalResults represents an accurate count.
   *
   * If False, it does not, and may be estimated/only the size of the current page.
   *
   * Either way, you should probably always only trust hasMore.
   *
   * This is a long-held historical throwback to when we used to do paging with known
   * total results. Those queries toasted our database, and we were left to hastily
   * alter our endpoints and create backward- compatible shims, of which
   * useTotalResults is one.
   */
  readonly useTotalResults: boolean;
}
export interface PostResponse {
  readonly lastReplyTimestamp: string;
  readonly IsPinned: boolean;
  readonly urlMediaType: ForumMediaType;
  readonly thumbnail: string;
  readonly popularity: ForumPostPopularity;
  readonly isActive: boolean;
  readonly isAnnouncement: boolean;
  readonly userRating: number;
  readonly userHasRated: boolean;
  readonly userHasMutedPost: boolean;
  readonly latestReplyPostId: string;
  readonly latestReplyAuthorId: string;
  readonly ignoreStatus: IgnoreResponse;
  readonly locale: string;
}
export declare const ForumMediaType: {
  readonly None: 0;
  readonly Image: 1;
  readonly Video: 2;
  readonly Youtube: 3;
};
export type ForumMediaType = (typeof ForumMediaType)[keyof typeof ForumMediaType];
export declare const ForumPostPopularity: {
  readonly Empty: 0;
  readonly Default: 1;
  readonly Discussed: 2;
  readonly CoolStory: 3;
  readonly HeatingUp: 4;
  readonly Hot: 5;
};
export type ForumPostPopularity = (typeof ForumPostPopularity)[keyof typeof ForumPostPopularity];
export interface PollResponse {
  readonly topicId: string;
  readonly results: PollResult[];
  readonly totalVotes: number;
}
export interface PollResult {
  readonly answerText: string;
  readonly answerSlot: number;
  readonly lastVoteDate: string;
  readonly votes: number;
  readonly requestingUserVoted: boolean;
}
export interface ForumRecruitmentDetail {
  readonly topicId: string;
  readonly microphoneRequired: boolean;
  readonly intensity: ForumRecruitmentIntensityLabel;
  readonly tone: ForumRecruitmentToneLabel;
  readonly approved: boolean;
  readonly conversationId?: string;
  readonly playerSlotsTotal: number;
  readonly playerSlotsRemaining: number;
  readonly Fireteam: GeneralUser[];
  readonly kickedPlayerIds: string[];
}
export declare const ForumRecruitmentIntensityLabel: {
  readonly None: 0;
  readonly Casual: 1;
  readonly Professional: 2;
};
export type ForumRecruitmentIntensityLabel =
  (typeof ForumRecruitmentIntensityLabel)[keyof typeof ForumRecruitmentIntensityLabel];
export declare const ForumRecruitmentToneLabel: {
  readonly None: 0;
  readonly FamilyFriendly: 1;
  readonly Rowdy: 2;
};
export type ForumRecruitmentToneLabel =
  (typeof ForumRecruitmentToneLabel)[keyof typeof ForumRecruitmentToneLabel];
export declare const CommunityContentSortMode: {
  readonly Trending: 0;
  readonly Latest: 1;
  readonly HighestRated: 2;
};
export type CommunityContentSortMode =
  (typeof CommunityContentSortMode)[keyof typeof CommunityContentSortMode];
