/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.21.9
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-ts code generator program.
 * https://github.com/DestinyItemManager/bungie-api-ts
 * Do not edit these files manually.
 */
export interface IgnoreResponse {
    readonly isIgnored: boolean;
    /**
     * This enum represents a set of flags - use bitwise operators to check which of
     * these match your value.
     */
    readonly ignoreFlags: IgnoreStatus;
}
/**
 * This enum represents a set of flags - use bitwise operators to check which of
 * these match your value.
 */
export declare const IgnoreStatus: {
    readonly NotIgnored: 0;
    readonly IgnoredUser: 1;
    readonly IgnoredGroup: 2;
    readonly IgnoredByGroup: 4;
    readonly IgnoredPost: 8;
    readonly IgnoredTag: 16;
    readonly IgnoredGlobal: 32;
};
export type IgnoreStatus = typeof IgnoreStatus[keyof typeof IgnoreStatus];
export interface TagResponse {
    readonly tagText: string;
    readonly ignoreStatus: IgnoreResponse;
}
