/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.21.9
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-ts code generator program.
 * https://github.com/DestinyItemManager/bungie-api-ts
 * Do not edit these files manually.
 */
import { BungieMembershipType } from '../common.js';
import { GeneralUser } from '../user/interfaces.js';
export declare const PlatformFriendType: {
  readonly Unknown: 0;
  readonly Xbox: 1;
  readonly PSN: 2;
  readonly Steam: 3;
  readonly Egs: 4;
};
export type PlatformFriendType = (typeof PlatformFriendType)[keyof typeof PlatformFriendType];
export interface BungieFriendListResponse {
  readonly friends: BungieFriend[];
}
export interface BungieFriend {
  readonly lastSeenAsMembershipId: string;
  readonly lastSeenAsBungieMembershipType: BungieMembershipType;
  readonly bungieGlobalDisplayName: string;
  readonly bungieGlobalDisplayNameCode?: number;
  readonly onlineStatus: PresenceStatus;
  /**
   * This enum represents a set of flags - use bitwise operators to check which of
   * these match your value.
   */
  readonly onlineTitle: PresenceOnlineStateFlags;
  readonly relationship: FriendRelationshipState;
  readonly bungieNetUser: GeneralUser;
}
export declare const PresenceStatus: {
  readonly OfflineOrUnknown: 0;
  readonly Online: 1;
};
export type PresenceStatus = (typeof PresenceStatus)[keyof typeof PresenceStatus];
/**
 * This enum represents a set of flags - use bitwise operators to check which of
 * these match your value.
 */
export declare const PresenceOnlineStateFlags: {
  readonly None: 0;
  readonly Destiny1: 1;
  readonly Destiny2: 2;
};
export type PresenceOnlineStateFlags =
  (typeof PresenceOnlineStateFlags)[keyof typeof PresenceOnlineStateFlags];
export declare const FriendRelationshipState: {
  readonly Unknown: 0;
  readonly Friend: 1;
  readonly IncomingRequest: 2;
  readonly OutgoingRequest: 3;
};
export type FriendRelationshipState =
  (typeof FriendRelationshipState)[keyof typeof FriendRelationshipState];
export interface BungieFriendRequestListResponse {
  readonly incomingRequests: BungieFriend[];
  readonly outgoingRequests: BungieFriend[];
}
export interface PlatformFriendResponse {
  readonly itemsPerPage: number;
  readonly currentPage: number;
  readonly hasMore: boolean;
  readonly platformFriends: PlatformFriend[];
}
export interface PlatformFriend {
  readonly platformDisplayName: string;
  readonly friendPlatform: PlatformFriendType;
  readonly destinyMembershipId?: string;
  readonly destinyMembershipType?: BungieMembershipType;
  readonly bungieNetMembershipId?: string;
  readonly bungieGlobalDisplayName: string;
  readonly bungieGlobalDisplayNameCode?: number;
}
